### ISSUE TITLE
Could not add a tuple.

### ISSUE THREAD

**Issue by annanurov** [gskielian/JPG-PNG-to-MNIST-NN-Format#11]
I could not add a tuple of color values to 'data_image':
 `data_image.append(pixel[y,x])`

Changed to  `
data_image.append(pixel[y,x][0])`
since images are grayscale. 

How to add the tuple in case all color channels are different?

Thank you.

**Comment by nerdykamil** [comment]
hey, did you find the solution yet? 
I was wondering if we could take three arrays like data_image1, data_image2, data_image3 and then add it to output file like data_image = header + data_image1 + data_image2 + data_image3
will that work?

**Comment by annanurov** [comment]
You could  average the channels or, in case of gray scale, take only one channel.
Both should work.

**Comment by Hariprasad-gowda** [comment]
import statistics

 if type(pixel[y, x]) is tuple:
                    p=statistics.mean(pixel[y, x])
 else:
                    p =pixel[y, x]

 data_image.append(int(p))

**Comment by annanurov** [comment]
Thank you guys.
Ending the issue here.

**Comment by annanurov** [comment]
...how do I end the issue?
