### ISSUE TITLE
'gzip' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ayangupt90** [gskielian/JPG-PNG-to-MNIST-NN-Format#22]
After completing execution of 90% part in this program, I've involved in a problem based on Operating System. I can't understand that what i need to change on PATH variable on "Environment Variable" section of OS. Just for convert data set into .gz file through this program i'm unable to go further part of my project. For convenience please see attachment of output:
![capture](https://user-images.githubusercontent.com/39652579/40615368-13a409bc-62a4-11e8-9e2f-5a569005ab73.PNG)

**Comment by Muhammadkamrul** [comment]
> After completing execution of 90% part in this program, I've involved in a problem based on Operating System. I can't understand that what i need to change on PATH variable on "Environment Variable" section of OS. Just for convert data set into .gz file through this program i'm unable to go further part of my project. For convenience please see attachment of output: ![capture](https://user-images.githubusercontent.com/39652579/40615368-13a409bc-62a4-11e8-9e2f-5a569005ab73.PNG)

How did you solve it?
