### ISSUE TITLE
  data_image.append(pixel[y,x]) TypeError: an integer is required

### ISSUE THREAD

**Issue by inakuhn** [gskielian/JPG-PNG-to-MNIST-NN-Format#8]
Traceback (most recent call last):
  File "convert-images-to-mnist-format.py", line 35, in <module>
    data_image.append(pixel[y,x])
TypeError: an integer is required
Do you know what can be wrong? 
i have 28x28px image

**Comment by fengchichenmo** [comment]
i meet same problem. how did you solve it?
@inakuhn
