### ISSUE TITLE
Where is the  batches.meta.txt file?

### ISSUE THREAD

**Issue by bemoregt** [gskielian/JPG-PNG-to-MNIST-NN-Format#9]
Hi, @gskielian 

Where is the image batches.meta.txt file?

I cannot change the file because of no file.

**Comment by delray** [comment]
+1 - im curious about this too...

**Comment by gskielian** [comment]
I added examples for the batches.meta.txt file in latest push -- this isn't used by the Python scripts but is useful later for Tensorflow processes, which can utilize this to map numerical labels with the labels in "batches.meta.txt" file.

This is more of an artifact of my "Png-2-Cifar10" repo which I adapted this from, but could be one way to keep track of your mapping of folder numbers to categories.
